### PR TITLE
Add unittest-xml-reporting

### PR DESCRIPTION
**Pull request by vtbassmatt**
Adds unittest-xml-reporting. This allows generating XUnit-compatible files for CI systems to consume.

### CODE REVIEW

**Comment by vtbassmatt** [comment]
@orf something I'm not sure I love is that this will automatically start emitting TEST-*.xml files into /tests/django/output in the container. I think if `$DJANGO_ROOT`/output doesn't exist in the host, you get a permissions error after the tests run.

A couple of options I wanted to bounce off you:
- Ignore the issue. In non-CI scenarios, the permissions error writing XMLs doesn't matter that much, and it's easy to fix.
- Add an environment variable to control the attempt. I think this would have to be plumbed through into each settings file (as an `import os; if os.environ['whatever'] ...`) by way of the docker-compose file. As a non-expert, I wasn't clear on the right pattern for that.
- Something else you can think of?

**Comment by vtbassmatt** [comment]
Thanks! And good catch on the missing TEST_RUNNER.

**Comment by orf** [comment]
Thank you for this @vtbassmatt! So I'm not a fan of the error (it shouldn't be happening at all really! the permissions should be fine), but with regards to the CI I think we can do the following:
1. All .xml files are written to `/test/results/`, which is outside of the `django/` mount point
2. If you're running a CI service that needs these, you need to run: `docker-compose run -v/test/results:your-result-dir sqlite`. Then the CI needs to read from `your-result-dir`?

This way we can hopefully get the best of both worlds: xml files are not placed into the django mount directory, are ignored if you're not a CI, and can be exposed easily if you are.

What do you think?

**Comment by vtbassmatt** [comment]
Let me give that a try tomorrow. I knew there had to be a way!

**Comment by vtbassmatt** [comment]
Yes, this absolutely looks like it's going to work. I see you already made the changes in the settings and Dockerfile - great! I think I just need you to push new images to Docker Hub so I can remove the "build the container" step.

**Comment by orf** [comment]
Awesome! I think this last step should have been handled by the current
Travis setup, so it should be live!

**Pull request merged**
